# Generated by Django 2.1.7 on 2019-04-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordVector',
            fields=[
                ('word', models.CharField(help_text='主键属性', max_length=4, primary_key=True, serialize=False)),
                ('vector', models.CharField(help_text='向量通过其 200 维的列表 json.dumps 为字符串后替换空字符存储，<br />计算得到这个字符串最长 2401，数据库中以最多 2500 字节存储', max_length=2500)),
            ],
        ),
    ]
