# Generated by Django 2.1.7 on 2019-04-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NlpComponent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordVectorCache',
            fields=[
                ('word', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('vector', models.CharField(max_length=2500)),
                ('call_times', models.IntegerField(default=1, editable=False, help_text='用于记录该项被调用次数的属性值')),
            ],
            options={
                'verbose_name': '词向量缓存',
                'verbose_name_plural': '词向量高速缓存数据库',
            },
        ),
        migrations.AlterModelOptions(
            name='wordvector',
            options={'verbose_name': '词向量', 'verbose_name_plural': '词向量数据库'},
        ),
        migrations.AlterField(
            model_name='wordvector',
            name='word',
            field=models.CharField(help_text='主键属性，最长 32 个字节', max_length=32, primary_key=True, serialize=False),
        ),
    ]
