# Generated by Django 2.1.7 on 2019-04-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='唯一标识，以字符串形式存储在数据库中的 pattern，最长 128 个字节', max_length=128, unique=True)),
                ('template', models.CharField(help_text='以字符串形式存储在数据库中的 template，最长 256 个字节', max_length=256)),
                ('that', models.CharField(help_text='以字符串形式存储在数据库中的 taht，最长 128 个字节', max_length=128)),
            ],
            options={
                'verbose_name': '模式对象',
                'verbose_name_plural': '模式表格',
            },
        ),
    ]
