# Generated by Django 2.1.7 on 2019-04-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FixedConv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiml',
            name='pattern',
            field=models.CharField(help_text='唯一标识，以字符串形式存储在数据库中的 pattern，最长 128 个字节', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='aiml',
            unique_together={('pattern', 'that')},
        ),
    ]
