# Generated by Django 2.1.7 on 2019-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherMsg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(help_text='必填项。老师的姓名，最多 32 个字符', max_length=32, verbose_name='姓名'),
        ),
    ]
