# Generated by Django 2.1.7 on 2019-04-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherMsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='depart',
            field=models.CharField(blank=True, help_text='老师的所属院系，最多 64 个字符', max_length=64, null=True, verbose_name='研究系属'),
        ),
    ]
