# Generated by Django 2.1.7 on 2019-04-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherMsg', '0002_auto_20190402_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='field',
            field=models.CharField(blank=True, help_text='老师的研究方向，最多 128 个字符', max_length=128, null=True, verbose_name='研究领域'),
        ),
    ]
